name: BackArt
description: An application for making background art.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  saver_gallery: ^4.0.1
  fluttertoast: ^8.2.12
  flutter_picker: ^2.1.0
  device_info_plus: ^11.5.0
  flutter_svg: ^2.2.0
  sqflite: ^2.4.2
  quick_actions: ^1.1.0
  sqflite_common: ^2.5.6
  url_launcher: ^6.3.2
  app_links: ^6.4.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated to the latest stable version
  lints: ^4.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/top_left.svg
    - assets/icons/top_right.svg
    - assets/icons/bottom_left.svg
    - assets/icons/bottom_right.svg
    - assets/icons/top_center.svg
    - assets/icons/bottom_center.svg
    - assets/icons/center.svg
    - assets/icons/center_left.svg
    - assets/icons/center_right.svg
    - assets/icons/github-mark.png
    - assets/icons/github-mark-white.png
    - assets/images/wechat_pay.jpg
    - assets/images/wechat_tip.jpg

  fonts:
    - family: OppoSans
      fonts:
        - asset: assets/fonts/OppoSans/medium.ttf
        - asset: assets/fonts/OppoSans/regular.ttf
        - asset: assets/fonts/OppoSans/bold.ttf
          weight: 700
    - family: HanaMin
      fonts:
        - asset: assets/fonts/HanaMin/HanaMinA.ttf
        - asset: assets/fonts/HanaMin/HanaMinB.ttf
          weight: 700
    - family: AllertaStencil
      fonts:
        - asset: assets/fonts/AllertaStencil/AllertaStencil-Regular.ttf
    - family: CabinSketch
      fonts:
        - asset: assets/fonts/CabinSketch/CabinSketch-Regular.ttf
        - asset: assets/fonts/CabinSketch/CabinSketch-Bold.ttf
          weight: 700
    - family: Foldit
      fonts:
        - asset: assets/fonts/Foldit/Foldit-VariableFont_wght.ttf
        - asset: assets/fonts/Foldit/static/Foldit-Regular.ttf
        - asset: assets/fonts/Foldit/static/Foldit-Medium.ttf
        - asset: assets/fonts/Foldit/static/Foldit-Bold.ttf
          weight: 700
    - family: Glegoo
      fonts:
        - asset: assets/fonts/Glegoo/Glegoo-Regular.ttf
        - asset: assets/fonts/Glegoo/Glegoo-Bold.ttf
          weight: 700
    - family: KellySlab
      fonts:
        - asset: assets/fonts/KellySlab/KellySlab-Regular.ttf
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/LXGWWenKai/LXGWWenKai-Regular.ttf
        - asset: assets/fonts/LXGWWenKai/LXGWWenKai-Light.ttf
        - asset: assets/fonts/LXGWWenKai/LXGWWenKai-Bold.ttf
          weight: 700
    - family: LXGWWenKaiMono
      fonts:
        - asset: assets/fonts/LXGWWenKai/LXGWWenKaiMono-Regular.ttf
        - asset: assets/fonts/LXGWWenKai/LXGWWenKaiMono-Light.ttf
        - asset: assets/fonts/LXGWWenKai/LXGWWenKaiMono-Bold.ttf
          weight: 700
    - family: Melete
      fonts:
        - asset: assets/fonts/Melete/Melete-Regular.otf
        - asset: assets/fonts/Melete/Melete-Medium.otf
        - asset: assets/fonts/Melete/Melete-Light.otf
        - asset: assets/fonts/Melete/Melete-Bold.otf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton/Monoton-Regular.ttf
    - family: Unifont
      fonts:
        - asset: assets/fonts/UnifontPixel/unifont.otf
    - family: UnifontJP
      fonts:
        - asset: assets/fonts/UnifontPixel/unifont_jp.otf
    - family: LXGWBright
      fonts:
        - asset: assets/fonts/LXGWBright/LXGWBright-Regular.ttf
        - asset: assets/fonts/LXGWBright/LXGWBright-Medium.ttf
        - asset: assets/fonts/LXGWBright/LXGWBright-Italic.ttf
          style: italic
    - family: FusionPixelJa
      fonts:
        - asset: assets/fonts/FusionPixelProportional/FusionPixel-ja.ttf
    - family: FusionPixelKo
      fonts:
        - asset: assets/fonts/FusionPixelProportional/FusionPixel-ko.ttf
    - family: FusionPixelLatin
      fonts:
        - asset: assets/fonts/FusionPixelProportional/FusionPixel-latin.ttf
    - family: FusionPixelZhHans
      fonts:
        - asset: assets/fonts/FusionPixelProportional/FusionPixel-zh_hans.ttf
    - family: FusionPixelZhHant
      fonts:
        - asset: assets/fonts/FusionPixelProportional/FusionPixel-zh_hant.ttf
    - family: SmileySans
      fonts:
        - asset: assets/fonts/SmileySans/SmileySans-Oblique.ttf
    - family: BackArt
      fonts:
        - asset: assets/fonts/BackArt/back_art.ttf
